# Angular and Meteor - The perfect stack https://www.angular-meteor.com/
#
# Author: Georgy Berdyshev
#

sudo: required
services:
  - docker
env:
  - distribution: ubuntu
    version: bionic
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=Dockerfile --tag=angular-meteor:latest .'
install:
  - 'sudo docker run -v ${TRAVIS_BUILD_DIR}:/angular-meteor/ angular-meteor:latest git clean -fXd'
  - 'sudo docker run -v ${TRAVIS_BUILD_DIR}:/angular-meteor/ angular-meteor:latest npm cache verify'
  - 'sudo docker run -v ${TRAVIS_BUILD_DIR}:/angular-meteor/ angular-meteor:latest npm install -g concurrently'
script:
  - 'sudo docker run -v ${TRAVIS_BUILD_DIR}:/angular-meteor/ angular-meteor:latest /angular-meteor/run_tests.sh'
