sudo: required
services:
  - docker
env:
  - distribution: ubuntu
    version: bionic
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "8"
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=Dockerfile --tag=angular-meteor'
  - npm install -g npm@latest
  - curl https://install.meteor.com | /bin/sh
install:
  - git clean -fXd
  - npm cache verify
  - npm install -g concurrently
script:
  - sh run_tests.sh