sudo: required
language: node_js
node_js:
  - "8"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - curl https://install.meteor.com | /bin/sh
install:
  - git clean -fXd
  - npm cache verify
  - npm install -g concurrently
script:
  - ./run_tests.sh
